# Generated by Django 4.0.1 on 2022-01-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='fisrtName',
            new_name='firstName',
        ),
    ]
