# Generated by Django 4.0.1 on 2022-01-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=20)),
                ('instructor', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
